# Publication Management

## Overview

Hubbard Brook publications are managed in Zotero. The primary database is on the IM desktop where publications are initially ingested.

## Zotero

On the IM desktop there is full access to publications through the UNH Library.

-   publications are identified through self-reporting to IM, google scholar searches, Hubbard Brook Monthly newsletters, and HBR LTER Annual Reports.
-   each update period is managed in a dated folder in zotero
-   by clicking zotero icon on pub landing page, it is ingested into Zotero (full citation plus accessible pdfs)
-   tagging identifies 'LTER', 'data-only', and last_f tags for each HB author (the latter facilitates Zotpress links to each person's profile on the website).
-   once tagged, the new pubs are copied to the HBR-LTER group folder.
-   the group folder is synced to the hubbardbrook Zotero cloud account. Syncing is set *not* to upload the pdfs, as this can violate copyright. Publications since \~2010 contain DOI links.

## EDI publication-data linkages

The EDI repository facilitates the linking of publications with underlying data through the 'add journal citation' feature. For HBR we add all known linkages. The EDI team has a semiautomated process where they identify new data DOI's in the literature and then they add the pubs to the datasets. This is not 100%, as some papers still slip up on proper data citation, or data publication lags paper publication. In this case, IM is on the lookout for instances where manual additions need to be made.

## Zotpress

This wordpress plugin on our website is linked to the cloud-based HB Zotero account and to displays publications on the people profile pages on website through tagging of last_f for each author on a publications.
