# RAC Proposal Submissions

## Overview

Proposals submitted to the Hubbard Brook Research Advisory Committee (RAC), are managed through the JotForm account at the Cary Institute. Calls for proposals go out to the research community for March and September deadlines. Information on the process is found on [proposal submission page](https://hubbardbrook.org/research-proposal-submission/) on the Hubbard Brook website.

## IM role in RAC submissions

Beginning in Spring 2023, the RAC proposals have been submitted through the Cary institute Jotform. Prior to this, the submission pathway was via website forms hosted at UNH (2008-2014) and google forms (2015-2023). The structure of the form was migrated to JotForm, and from 2023-2024 a number of enhancements have been made. The Hubbard Brook sharepoint RAC folder contains a backup of all proposals. Admin access to the JotForm can be obtained from IT support at the Cary Institute.

Form related tasks are carried out by the HBR IM (under direction of RAC chair) to include:

-   Development of a clone of the old website form on the Cary JotForm account

-   Add enhancements as requested by RAC chair

-   Monitor incoming proposal

-   Prepare proposals for review by RAC (export individually as pdf, and in an appended pdf format).

-   HBR IM reaches out to accepted proposal leads to let them know how we archive data in the repository at HBR, what the IM needs to know about their data collection, and what assistance can be provided to them by the IM. See [email template](TBD)

-   JotForm technical details in appendices below

-   NOTE: Access to all submissions in the JotForm environment can be made available to the RAC chair. In this scenario, there are enhanced features where the proposals could be flagged as ‘under review’, ‘accepted’, etc. And the chair could manage their own downloads of proposals.

## RAC data publishing instructions

Although not in the form itself, the following text is used in the RAC proposal acceptance letter:

> The Hubbard Brook Ecosystem Study preserves and shares data through the Environmental Data Initiative Repository (EDI). Projects supported through NSF LTER funding, follow the LTER data access requirement. In order to maintain a one-stop data catalog for all site research, we encourage all researchers, regardless of funding source, to preserve their data in a similar manner. Support for this process is available through the Hubbard Brook Information Management Team. Please contact Mary Martin about preparing your data. Please let me know once you have met with Mary and addressed any data format questions that you have.

## Jotform Tips

-   Edit form allows for insertion and editing of form blocks as necessary.

-   More/submissions provides access to all submitted proposals

-   On the top left, the pdf editor allows you to check all fields to be included in the report. By default, this does not include the file upload links. Scroll down to this, check file upload and this will now be inserted in each proposal pdf output.

-   The links to uploaded assets that are included in with the submission are publicly accessible by link (uploaded images are displayed in the pdf), so reviewers do not need any special permission to view these uploaded files. Uploaded images are displayed in the pdf, other filetypes by link.

-   Download All will create a zip file with each proposal in a separate file.

-   To append all files, use: pdfjam file1 file1 file3 ... -o RAC-proposals_YYYY\[spring,fall\].pdf
