# Physical Sample Archive

## Overview

The Hubbard Brook Experimental Forest (HBEF) is operated and maintained by the USDA Forest Service, Northern Research Station. Research at HBEF began in the 1960’s and the research community consists of investigators from numerous institutions across the US (and world). Collectively, this research has been funded by the USDA Forest Service, National Science Foundation, Department of Energy, US Geological Survey, other federal grant programs, and private foundation funds. Research projects have generated a wealth of samples, preserved in either the on-site sample archive facility located at HBEF and/or numerous institutional collections (biological voucher samples).  

The Hubbard Brook Physical Sample Archive was completed in 1990 to permanently store research samples for future use in Hubbard Brook studies. The building provides a special and unique opportunity to maintain a research memory for long term ecosystem studies. To date there are 70,000 barcoded and cataloged samples ranging from water samples to soils and plant parts. Samples from ongoing, long-term collections and shorter-term projects are included. Cataloged samples are accessible on-line in a public searchable database and are available for subsampling in support of new studies and additional analyses. Stored and catalogued samples have been used to address scientific questions and have resulted in additional publications featuring archived sample analysis. [add link to list of published papers using archived samples]

The archive is managed to accommodate future sample submissions. Samples from Hubbard Brook are accepted into the archive system if they are likely to be of future use and are accompanied by adequate documentation. Detailed metadata is submitted with each sample and stored in a relational database. The Hubbard Brook website provides browse/search/filter access to the sample database at both the collection and sample level. 

External collections have been used extensively since the 1960’s for the preservation of biological voucher specimens. A 2024 assessment of HB voucher samples identified more than 2000 samples in 40+ collections in the US and Canada. With the growing acceptance of digitial (image/audio) vouchers, this number grows to several hundred thousand. Management and policies for samples and specimens in external collections are addressed in a separate document. See [voucher sample chapter](VoucherSamples.qmd) for more details.

## Sample archive database

The sample archive database is managed by the Hubbard Brook USFS. Sample metadata are processed from submission spreadsheet templates (L0) to harmonized tables (L1) to appended files for accessions, collections, and samples (L2). The workflow and products occurs in the USFS Pinyon (BOX) environment. L2 files are staged with URL access for the Rshiny sample search app.

## Templates/Forms

Templates for submitting a new accession can be found [here](link)

Sample subsetting request form can be found [here](subsampling_request.pdf)

## Rshiny

The interface for searching and downloading samples of interest is developed in Rshiny. This app allows search at the collection level and full sample search across all collections. The R shiny code is in a separate [GitHub repository](link)

## Management Plan

Under development and maintained in a seperate document, to cover:

- Archive Location and Infrastructure
- Sample Accession – Policies and Procedures
- Sample Identification and Documentation
- Data Management
- Metadata lifecycle
- Access and Permissions
- Disposal and Deaccessioning