
# Computer Resources

# IT Resources {#it-resources}

IT support for the UNH IM team is available through the UNH Research Computer Center (RCC). RCC provides support to researchers in the Institute for the Study of Earth, Oceans, and Space, as well as to the wider University research community, State of NH, and Federal Agencies. ESRC has had a long-standing Service Level Agreement (SLA) with RCC (more than 20 years) which can be provided to reviewers upon request. In addition to overall IT support described in the SLA, RCC also provides the personnel for as-needed project support. This gives the HBR-IM team access to expertise for special projects, without the need to provide ongoing support for personnel on the IM team for programming, web design, etc. HBR-IM has also made use of an *RCC-funded* internship program, wherein computer science undergraduates are paired with researchers in the Institute for Earth, Oceans, and Space.

## Software used by IM

Table 1 outlines software in use by HBR-IM to manage data package development and the Hubbard Brook website.

Table 1. Features of HBR Information Management System

| **Feature**                                                    | **Details, software, resources**                                         |
|-------------------------------------|-----------------------------------|
| Website: [https://hubbardbrook.org](https://hubbardbrook.org/) | WordPress, html, css, php, xslt, javascript, apache, piwigo              |
| Bibliography                                                   | Zotero, Zotpress wordpress plugin                                        |
| Data Catalog                                                   | EDI data repository, local WordPress gateway to EDI HBR data, EDIutils R |
| Metadata                                                       | ezEML, PostgreSQL, EML R package, EML2.1                                 |
| Computer Hardware                                              | Dell Poweredge R510, desktop and laptop linux systems.                   |
| Backup                                                         | BackupPC, rsnapshot, daily, weekly and monthly backups, on and off-site  |
| Data management                                                | R, LibreOffice, QGIS, MySQL, PostgreSQL, git                             |


## Account access

A number of accounts require access for HBR Information Management. 
In some cases, access can be granted through the UNH Research Computing Center, and in other cloud-based accounts the IM has designated a backup person to have account access.

-   IM desktop and server [IM/RCC]
-   UNH HB sharepoint [IM/Contosta at unh]
-   Zotero [IM/BU]
-   Databases [IM/RCC]
-   Piwigo [IM/RCC]
-   EDI/ezEML [IM/EDI]
-   Jotform [IM/Keeling at Cary]
-   Bluehost [IM/Post at 6288media]
-   GitHub
-   hubbardbrook gmail [IM/BU]

## Computer Resources

The Earth Systems Research Center's (ESRC) Science Computing Facility (SCF) has a wide range of computer servers, printers, plotters, archiving systems, software, data archives, and web based data distribution systems that are integrated using several internal networks and connected to the outside world through a high speed pipe. The overall SCF administration is provided by the Research Computing Center (RCC) located in the Institute for the Study of Earth, Oceans and Space (EOS). Scientific data processing and analysis support is distributed throughout workgroups within the center with additional centralized expertise provided by ESRC's Laboratory for Remote Sensing and Spatial Analysis. RCC's Lenharth Data Center was upgraded in September 2011. This upgrade brought in new APC UPS units, energy efficient in-rack cooling systems, and monitoring hardware to provide more space and capability for future growth. Within this proposal, we take advantage of this existing computer infrastructure, to meet our anticipated computational needs.

The main ESRC servers consist of high-end, multi-processor computing systems manufactured by Dell. The Dell systems run Linux and are used for CPU intensive jobs, parallel modeling, and storage. Backups and archives are done using BackupPC a disk-to-disk based system. Most of the main servers share a gigabit (Gb) switch with the archive/backup system for high-speed communications. All of this equipment is kept within a physically secured, humidity and temperature controlled data center complete with closed circuit video surveillance and a remotely monitored security alarm system. Final data and image products are produced from several ink-jet plotters and laser printers within the department. Additionally, several CD/DVD writers are used for data distribution.

EOS includes a CRAY XE6m-200 with 132 nodes, over 4000 processors and 160Tb of storage. In addition, our infrastructure has been strategically upgraded to provide gigabit networking to desktops.

Individual scientists and research groups have additional computing resources at their disposal. These include dedicated servers, individual workstations, and various peripheral devices. The group servers and individual workstations include: Linux servers and workstations, Windows workstations, Apple Macintosh desktop and laptop computers. All servers, user systems and networked peripheral devices are accessible within EOS through a gigabit ethernet network. Wireless networking is available throughout the building, including access to EduRoam. These systems also have access to both Internet 1 and Internet 2.

ESRC currently houses a 65TB+ geographically referenced data archive used for spatial data processing and analysis. This archive stored on RAID5 data disks served by a series of data servers, houses global, regional and local, Landsat, MODIS, IKONOS, Hyperion, ASTER, and SPOT satellite imagery, land cover classified products, vegetation and other indexes (EVI, LSWI, NDSI, NDVI, NDWI, LAI), aerial photography and GIS vector data layers for use by all projects within the department. Portions of these data, processed data products, and project results archive are disseminated and distributed through several dozen regularly updated and maintained ESRC operated websites. These websites are served through a variety of web servers running Apache web server software supported by other applications and libraries such as Tomcat, Web Mapping Server (WMS), OpenLayers and other geographically enhanced libraries such as GDAL, PROJ4, and GCTP.

ESRC also leverages the center's Laboratory for Remote Sensing and Spatial Analysis, a spatial information processing, analysis and distribution research laboratory. This laboratory provides geographic information system (GIS), Web Mapping, spatial data archiving, data distribution, remote sensing, image processing, cartography, large format printing and scanning support to several ESRC and EOS research projects. Staffed by professional geo-spatial information technicians, computer programmers, and graduate and undergraduate university students, the laboratory houses a multiple seat Linux, PC, and Mac OS computer cluster supplied with a variety of open source Remote Sensing, GIS, web mapping, image processing and cartography software and ESRI ArcGIS, Leica ERDAS Imagine, and IDL/ENVI, commercial site, block, and individually licensed GIS and Image processing software.
